### ISSUE TITLE
Feature Request:  Timestamp in Source Control Output

### ISSUE THREAD

**Issue by imukai** [mike-ward/VSColorOutput#20]
Not so much an issue as a request.

If it is not a monumental task, could you add an option to include Timestamps in the source control output window (e.g. Source Control - Team Foundation Server) to be able to see when files come in?

I don't use Git within VS but I would imagine there is a similar window for its activity as well.

**Comment by mike-ward** [comment]
The current timestamp implementation is relative to the debug session start time.

This doesn't seem appropriate for the for the source control output window. Sounds like time-of-day is what you want here.

Do you agree?

**Comment by JohnLudlow** [comment]
I was going to ask for the same thing, but for the build output.

**Comment by mike-ward** [comment]
Timestamps in the build output? What's the use case out of curiosity? I'm not opposed. Just surprised.

**Comment by JohnLudlow** [comment]
The use case is similar to the debug output, I think - identifying things that are taking too long.

Some of our solutions take significant time to build. While there are other ways to figure this out (`msbuild /detailedSummary` on the command line, for example) but this would allow us to at least get some kind of answer to questions like _hey, why'd that compile I just did in VS take so long?_

**Comment by mike-ward** [comment]
Sounds reasonable. I'll add it to the feature list.

**Comment by JohnLudlow** [comment]
Nice.

Thanks very much :+1:

**Comment by imukai** [comment]
> The current timestamp implementation is relative to the debug session start time. This doesn't seem appropriate for the for the source control output window. Sounds like time-of-day is what you want here. Do you agree?

Sorry for the late reply but yes I agree - time-of-day for that panel would be more appropriate.

I was thinking also that this might be too much scope creep for VSColorOutput and maybe it's time for VSTimestampOutput?  :)

**Comment by mike-ward** [comment]
Or I could just rename it to VSResharperOutput :smile:

**Comment by ZwergNaseXXL** [comment]
Used your build time feature today for the first time because the VS2013 builtin timing is way too detailed and is lacking the total time. VSColorOutput does just the right thing, total build time and nothing else. Thank you for that. 
However, I have one small issue with it: The last two digits are milliseconds, right? So I guess `var time = elapsed.ToString(@"hh\:mm\:ss\.ff");` should rather be `var time = elapsed.ToString(@"hh\:mm\:ss\.fff");` or something like that, making it three digits. Not that milliseconds really matter that much in this scenario, but still...

**Comment by mike-ward** [comment]
You're right. I'll fix it.

**Comment by ZwergNaseXXL** [comment]
Hi Mike, one more really minor issue: When no build is required (everything is up to date), the time stamp is still displayed, but displays the time passed since the last build. You might actually call that a feature. Unfortunately, the time will overflow after 100 hours, which just happened to me after the long easter weekend.

**Comment by mike-ward** [comment]
Interesting. Can you log this as a separate bug?
