### ISSUE TITLE
Current List Location is overridden by VSColorOutput on startup

### ISSUE THREAD

**Issue by omnigoat** [mike-ward/VSColorOutput#34]
Setting errors to be coloured red is great and all, until highlighting the line in the Output Window colours the line Red-On-Blue, which is unreadable. Visual Studio has an option to change this behaviour (`Options -> Fonts and Colors -> Show Settings For: Output Window -> Display Items: Current List Location`). Changing this to anything<sup>[1]</sup> (try a nice silver) fixes this. However, upon restarting Visual Studio, VSColorOutput nukes this, and Visual Studio once again highlights the selected line with the foreground colour as specified in VSColorOutput. The setting in Fonts and Colors remains the same (silver in this case), but isn't applied.

This occurs using both the Light and Dark themes.

**[1]** Visual Studio itself has a bug here: If the current selection is Default, and the Default colour is [ex.] White, and you select White, Visual Studio doesn't change anything.

**Comment by mike-ward** [comment]
VSColorOutput doesn't touch selection colors. VSColorOutput can't change the color of a line, only its classification. Since VSColorOutput doesn't set a classification for selections it's hard to imagine how it could nuke the selection color. I've long suspected that VS makes some decisions about color combinations that are outside the control of the span classification logic.
