### ISSUE TITLE
VS 2017 Hangs if build is broken when using VSColorOutput

### ISSUE THREAD

**Issue by ebonato** [mike-ward/VSColorOutput#56]
Using latest VS 2017 Community (15.2 - 26430.12) and VSColorOutput 2.5.1, if you try to build something tha has build errors, Visual Studio will hang indefinitely. After switching off more than 50 extensions, and re-enabling one-by-one, I came across that VSColorOutput was the failing extension.
Doesn't matter the project(simple/complex or tiny/huge), if you have an build error, VS2017 will hang.

**Comment by mike-ward** [comment]
I appreciate the bug report but I have to think it's something specific to your environment. A while back I had a similar issue which turned out to be another extension stepping on VSColorOutput. The other extension had to fix the issue since it was on their end (Good guys for doing that). Not shirking responsibility but build errors hanging  VS would have surfaced long before this. 2.5.1 only changes the manifest to limit support to VS2017. For the record, I'm running the same build of VS2017

![image](https://user-images.githubusercontent.com/567927/26880090-536bf1f0-4b61-11e7-97df-7ef72a211ce2.png)

If you're so inclined you might want to spool up a VM and with a fresh install of VS and see if it happens there.

**Comment by fr8tra1n** [comment]
I am experiencing similar issues using VS Enterprise 2017 (15.2 - 26430.15) and VSColorOutput 2.5.1. I have reinstalled VS2017 and various extensions, including vscoloroutput 2.5.1, and the issues are persisting.

**Comment by sleepy-byte** [comment]
Same thing over here with VS Enterprise 2017. 
Tried other colored output extension and it didn't crash.

**Comment by mike-ward** [comment]
Try turning off "Stop on First Build Error" and see if that makes a difference.

**Comment by mike-ward** [comment]
See issue #108
