### ISSUE TITLE
Adding support for the command prompt escape sequences.

### ISSUE THREAD

**Issue by galop1n** [mike-ward/VSColorOutput#62]
The visual studio output window lack the ability to interpret ANSI escape sequences ( see here : https://stackoverflow.com/questions/2048509/how-to-echo-with-different-colors-in-the-windows-command-line ) but VSColorOutput could catch them and interpret them prior to display.

**Comment by mike-ward** [comment]
When do ANSI escape sequences get echoed? Also, VSColorOutput is line oriented so there would be limitations.

**Comment by kbalint** [comment]
For example when a nodejs call is part of the build process:

![image](https://user-images.githubusercontent.com/4146263/157265652-af16e00e-2e2d-425e-ae07-d6943dedcfa8.png)

**Comment by mike-ward** [comment]
The problem is Visual Studio won't let VSColorOutput change the content of the line it is analyzing. It can only add classifications to the line structure or a region of the line structure. When the line is rendered, Visual Studio consults a Classification Map to decide how to render it (color and font weight only).
